// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllDU5Z9Lhhi-tsQzePxGwIepSInWa3pg',
    appId: '1:48087734684:web:061e4360a1bc5ba6b85059',
    messagingSenderId: '48087734684',
    projectId: 'lordschoolp',
    authDomain: 'lordschoolp.firebaseapp.com',
    storageBucket: 'lordschoolp.appspot.com',
    measurementId: 'G-PV30WLVBYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpIiqDqla9HtWSfENKg9BJQHCyfV4qh4',
    appId: '1:48087734684:android:85a8e4393821ad82b85059',
    messagingSenderId: '48087734684',
    projectId: 'lordschoolp',
    storageBucket: 'lordschoolp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_5uUZETizhBGJ6iyJbCWYbRLo4FNi_g',
    appId: '1:48087734684:ios:7500faaf8e26100cb85059',
    messagingSenderId: '48087734684',
    projectId: 'lordschoolp',
    storageBucket: 'lordschoolp.appspot.com',
    iosClientId: '48087734684-ihs13njj73igd0c2a6aejcach1f6mp4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lordsSchoolp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_5uUZETizhBGJ6iyJbCWYbRLo4FNi_g',
    appId: '1:48087734684:ios:7500faaf8e26100cb85059',
    messagingSenderId: '48087734684',
    projectId: 'lordschoolp',
    storageBucket: 'lordschoolp.appspot.com',
    iosClientId: '48087734684-ihs13njj73igd0c2a6aejcach1f6mp4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lordsSchoolp',
  );
}
